name: deploy-policy-DSO

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'

jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sedstuff
        run: find . -type f -exec sed -i 's@/c5fddee6-8712-4dd8-b580-637b37dc5472@g' {} \;

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: 875e5c0e-0ce2-4870-bec1-aafce4f65844
          tenant-id: a8bacb9e-c262-4477-b2fc-f69e5e619e61
          allow-no-subscriptions: true

      - name: Create or Update Azure Policies
        uses: azure/manage-azure-policy@v0
        with:
          paths: |
            .
          assignments: |
            policyset.json
