name: deploy-policy-DSO

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'

jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sedstuff
        run: find . -type f -exec sed -i 's@/c5fddee6-8712-4dd8-b580-637b37dc5472@g' {} \;

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: 449d0493-4b3a-4a76-ae09-4381769332c20
          tenant-id: 831de134-d871-4cd7-823a-eacb69c699c8
          allow-no-subscriptions: true

      - name: Create or Update Azure Policies
        uses: azure/manage-azure-policy@v0
        with:
          paths: |
            policy-sandbox.json
          assignments: |
            policyset.json
